const FaceTracking = require('FaceTracking');
const Scene = require('Scene');
const FaceMesh = require('FaceMesh');
const Materials = require('Materials');
const Textures = require('Textures');
const Reactive = require('Reactive');
const Animation = require('Animation');
const Diagnostics = require('Diagnostics');
const TouchGestures = require('TouchGestures');
const CameraInfo = require('CameraInfo');
const Patches = require('Patches');
const Random = require('Random');
// const DeviceMotion = require('DeviceMotion');
const Time = require('Time');
const Instruction = require('Instruction');
// Diagnostics.log(Instruction);